site_name: IntegralSTOR UNICell
site_description: Project documentation for the IntegralSTOR UNICell storage system.
site_url: https://github.com/integralstor/integralstor_unicell
repo_url: https://github.com/integralstor/unicell_admin_docs

pages:
  - Home: index.md
  - Getting started:
    - Network access configuration: initial/network_access.md
  - IntegralView:
    - Accessing IntegralView: integral_view/accessing.md
    - Changing the IntegralView password: integral_view/changing_password.md
    - Getting familiar with IntegralView: integral_view/getting_familiar.md
    - Change IntegralView access mode (secure/non-secure): integral_view/switching_modes.md
  - System information:
    - Viewing system information: system_configuration/intro.md
    - Scanning for hardware changes: system_configuration/scanning.md
    - Download system configuration: system_configuration/download.md
    - Configuring email alerts: system_configuration/email.md
  - ZFS storage operations:
    - ZFS concepts and terminology: zfs/intro.md
    - Supported storage layouts: zfs/storage_layouts.md
    - ZFS Pool operations:
      - Viewing ZFS pools: zfs/view_zfs_pools.md
  - Local users and groups:
    - Introduction : users_groups/intro.md
    - Viewing users or groups : users_groups/viewing_users_groups.md
    - Creating a user or group : users_groups/creating_user_group.md
    - Changing a user's password : users_groups/changing_user_password.md
    - Remove a user account : users_groups/remove_user.md
    - Modifying a user's group membership : users_groups/change_user_groups.md
    - Remove a group account : users_groups/remove_group.md
    - Modifying a group's membership : users_groups/change_group_users.md
  - Logging and alerting:
    - Introduction: logging/intro.md
    - Viewing logs: logging/view_logs.md
    - Rotating audit and alert logs: logging/rotate_logs.md
    - Viewing rotated logs: logging/view_rotated_logs.md
    - Downloading logs: logging/download_logs.md
  - Network configuration:
    - Introduction: networking/intro.md
    - Viewing interfaces & bonds: networking/view_interfaces.md
    - Viewing and configuring individual interfaces & bonds: networking/view_interface.md
    - Configuring network addresses: networking/configure_address.md
    - Changing interface status: networking/change_interface_state.md
    - Create a network bond: networking/create_bond.md
    - Removing a network bond: networking/remove_bond.md
    - Configuring the hostname and domain name: networking/configure_hostname.md
    - Configuring DNS name servers: networking/configure_dns.md
    - Viewing VLANs for an interface: networking/view_vlans.md
    - Creating a VLAN for an interface: networking/create_vlan.md
    - Configuring a VLAN address: networking/configure_vlan.md
    - Removing a VLAN : networking/remove_vlan.md
  - Background tasks:
    - Introduction: background_tasks/intro.md
    - Viewing all background tasks: background_tasks/view_tasks.md
    - Viewing background task details: background_tasks/view_task_details.md
    - Removing a task : background_tasks/remove_task.md
  - Replication and snapshots:
    - Introduction: replication_snapshots/intro.md
    - Viewing snapshots: replication_snapshots/view_snapshots.md
    - Creating a snapshot: replication_snapshots/create_snapshot.md
    - Snapshot operations: replication_snapshots/snapshot_operations.md
    - View snapshots schedules: replication_snapshots/view_snapshot_schedules.md
    - Modify snapshots schedules: replication_snapshots/modify_snapshot_schedules.md
    - Create a new snapshots schedule: replication_snapshots/create_snapshot_schedule.md
    - Viewing remote replications: replication_snapshots/view_remote_replications.md
    - Scheduling a remote replications: replication_snapshots/schedule_remote_replication.md
    - Modifying the schedule for a remote replications: replication_snapshots/modify_remote_replication.md
    - Cancelling the schedule for a remote replications: replication_snapshots/cancel_remote_replication.md
  - Services management:
    - Introduction: services/intro.md
    - Controlling services: services/controlling_services.md
    - Configuring the NTP service: services/configure_ntp.md
    - Configuring Windows access: services/configure_cifs.md
    - Configuring FTP access: services/configure_ftp.md
  - Data backup:
    - Introduction: backup/intro.md
  - Disk management:
    - Viewing disks: disks/view_disks.md


theme: readthedocs
